#!/usr/bin/env bash
# This script displays messages and handles signals

echo $$ > /var/run/myscript.pid 

trap 'rm -f /var/run/myscript.pid; exit 0' SIGTERM SIGQUIT
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 1
done

