#!/bin/bash
# Display time from 0:01 to 12:59

hours=0
while [ $hours -le 12 ]
do
  minutes=1
  while [ $minutes -le 59 ] 
  do
    echo "$hours:$minutes"
    minutes=$((minutes+1))
  done
  
  hours=$((hours+1))
done
