#!/usr/bin/env bash
# Configures localhost and facebook.com IP addresses 

cp /etc/hosts ~/hosts.cpy
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.cpy
cp -f ~/hosts.cpy /etc/hosts
